#!/bin/bash

if [ "$#" -lt 2 ]; then
  echo "Usage: $0 login password"
  exit 1
fi

login=$1
passw=$(perl -e 'print crypt($ARGV[0], "password")' $2)
home=/home/$login
keys=authorized_keys

locale-gen en_US.UTF-8

useradd --user-group --groups sudo --create-home --password $passw --shell /bin/bash $login
chage -d 0 $login

mkdir $home/.ssh
cat $keys >> $home/.ssh/authorized_keys

chmod 700 $home/.ssh
chmod 600 $home/.ssh/*

chown -R $login $home/.ssh
chgrp -R $login $home/.ssh

sed -i 's|^\(AcceptEnv LANG LC_*\)|#\1|' /etc/ssh/sshd_config
sed -i 's|^#\(PasswordAuthentication\) \(yes\)|\1 no|' /etc/ssh/sshd_config
sed -i 's|^\(PermitRootLogin\) yes|\1 no|' /etc/ssh/sshd_config

/etc/init.d/ssh restart

iptables -P INPUT DROP
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A INPUT -p tcp -m tcp --tcp-flags FIN,SYN,RST,PSH,ACK,URG NONE -j DROP
iptables -A INPUT -p tcp -m tcp ! --tcp-flags FIN,SYN,RST,ACK SYN -m state --state NEW -j DROP
iptables -A INPUT -p tcp -m tcp --tcp-flags FIN,SYN,RST,PSH,ACK,URG FIN,SYN,RST,PSH,ACK,URG -j DROP
iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
iptables -A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
iptables -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
iptables -A INPUT -j DROP

apt-get -qq update
apt-get -qq install make git software-properties-common iptables-persistent tmux

add-apt-repository -y ppa:chris-lea/node.js
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list

apt-get -qq update
apt-get -qq install nodejs

